"use client";
import {useState} from "react";

type Lang="ko"|"en"|"ja"|"zh";
const store="https://smartstore.naver.com/cake";
const words={
ko:{nav:["제품","활용","브랜드"],shop:"스토어",tag:"EDIBLE PRINTING, REIMAGINED",title:"당신의 이야기를\n먹을 수 있는 예술로.",desc:"선명한 사진, 브랜드 로고, 마음을 담은 문장까지. 케익살롱 아이싱시트 한 장으로 평범한 디저트를 가장 특별한 장면으로 바꿔보세요.",cta:"제품 보러가기",note:"대한민국에서 만드는 프리미엄 식용 프린팅",collection:"가장 사랑받는\n케익살롱 컬렉션",cards:[["A4 아이싱시트","홈베이킹부터 전문 제작까지","50 sheets"],["맞춤 포토 토퍼","사진 한 장으로 완성하는 기념일","Custom print"],["브랜드 솔루션","카페·호텔·기업 이벤트 맞춤 제작","B2B order"]],why:"예쁘게 인쇄되고,\n쉽게 사용할 수 있도록.",features:[["01","VIVID","사진과 로고를 또렷하고 섬세하게"],["02","EASY","필름에서 분리해 가볍게 올리기"],["03","VERSATILE","케이크·쿠키·컵케이크·음료까지"]],story:"한 장이 만드는\n큰 차이",storyDesc:"축하하는 마음도, 브랜드의 인상도 가장 맛있는 방식으로 전달합니다. 케익살롱은 디저트 위의 작은 공간을 오래 기억되는 경험으로 만듭니다.",final:"오늘의 디저트를\n작품으로 바꿔보세요.",call:"맞춤 제작 상담 080-664-7077"},
en:{nav:["Products","Ideas","Brand"],shop:"Shop",tag:"EDIBLE PRINTING, REIMAGINED",title:"Turn your story into\nedible art.",desc:"Vivid photos, brand logos, and heartfelt words. One Cake Salon icing sheet transforms an everyday dessert into an unforgettable scene.",cta:"Explore products",note:"Premium edible printing made in Korea",collection:"The most-loved\nCake Salon collection",cards:[["A4 Icing Sheets","For home bakers and professionals","50 sheets"],["Custom Photo Topper","Make celebrations personal with one photo","Custom print"],["Brand Solutions","Made for cafés, hotels and corporate events","B2B order"]],why:"Beautifully printed.\nEffortlessly applied.",features:[["01","VIVID","Crisp detail for photos and logos"],["02","EASY","Simply peel from the film and place"],["03","VERSATILE","For cakes, cookies, cupcakes and drinks"]],story:"One sheet.\nA world of difference.",storyDesc:"Share a celebration or express a brand in the most delicious way. Cake Salon turns a small space on dessert into a lasting experience.",final:"Turn today’s dessert\ninto a work of art.",call:"Custom orders +82 80-664-7077"},
ja:{nav:["商品","活用例","ブランド"],shop:"ストア",tag:"EDIBLE PRINTING, REIMAGINED",title:"物語を、\n食べられるアートへ。",desc:"鮮やかな写真、ブランドロゴ、心を込めた言葉まで。ケーキサロンのアイシングシートで、いつものデザートを特別なシーンに。",cta:"商品を見る",note:"韓国で作るプレミアム食用プリント",collection:"愛される\nケーキサロンコレクション",cards:[["A4アイシングシート","ホームベーキングからプロまで","50 sheets"],["オーダーフォトトッパー","一枚の写真で記念日を特別に","Custom print"],["ブランドソリューション","カフェ・ホテル・企業イベント向け","B2B order"]],why:"美しく印刷、\n使い方は簡単。",features:[["01","VIVID","写真とロゴを鮮明に表現"],["02","EASY","フィルムからはがしてのせるだけ"],["03","VERSATILE","ケーキ・クッキー・ドリンクまで"]],story:"一枚が生む、\n大きな違い。",storyDesc:"お祝いの気持ちも、ブランドの印象も、おいしい方法で伝えます。デザートの小さな空間を忘れられない体験へ。",final:"今日のデザートを\n作品に変えよう。",call:"オーダー相談 +82 80-664-7077"},
zh:{nav:["产品","灵感","品牌"],shop:"商店",tag:"EDIBLE PRINTING, REIMAGINED",title:"将故事变成\n可以品尝的艺术。",desc:"鲜明照片、品牌标志与暖心文字，一张 Cake Salon 糖霜纸，让普通甜点成为难忘的画面。",cta:"浏览产品",note:"韩国制造的优质可食用打印",collection:"备受喜爱的\nCake Salon 系列",cards:[["A4 糖霜纸","适合家庭烘焙与专业制作","50 sheets"],["定制照片装饰","用一张照片纪念特别时刻","Custom print"],["品牌解决方案","适合咖啡馆、酒店与企业活动","B2B order"]],why:"精美打印，\n轻松使用。",features:[["01","VIVID","清晰呈现照片与标志"],["02","EASY","从底膜揭下即可放置"],["03","VERSATILE","适用于蛋糕、曲奇与饮品"]],story:"一张纸，\n带来巨大不同。",storyDesc:"以最美味的方式传递祝福与品牌印象。Cake Salon 让甜点上的小空间成为长久记忆。",final:"让今天的甜点\n成为艺术品。",call:"定制咨询 +82 80-664-7077"}}
const Lines=({children}:{children:string})=><>{children.split("\n").map((x,i)=><span key={x}>{x}{i===0&&<br/>}</span>)}</>;
export default function Home(){const[lang,setLang]=useState<Lang>("ko");const t=words[lang];return <main>
<header><a className="logo" href="#top"><b>CAKE</b><i>SALON</i></a><nav>{t.nav.map((n,i)=><a key={n} href={["#products","#ideas","#brand"][i]}>{n}</a>)}</nav><div className="tools"><select aria-label="Language" value={lang} onChange={e=>setLang(e.target.value as Lang)}><option value="ko">KR</option><option value="en">EN</option><option value="ja">JP</option><option value="zh">CN</option></select><a href={store} target="_blank" rel="noreferrer">{t.shop} ↗</a></div></header>
<section className="hero" id="top"><div className="heroText"><p className="tag">{t.tag}</p><h1><Lines>{t.title}</Lines></h1><p className="desc">{t.desc}</p><a className="cta" href={store} target="_blank" rel="noreferrer">{t.cta}<b>↗</b></a><p className="made">● {t.note}</p></div><div className="heroVisual"><div className="poster p1"><small>YOUR IMAGE</small><strong>MAKE IT<br/>MEMORABLE</strong></div><div className="poster p2"><small>EDIBLE ART</small><strong>CAKE<br/>SALON</strong></div><div className="cake"><span>HAPPY<br/><b>DAY!</b></span></div><p className="vertical">PRINT · PEEL · PLACE · CELEBRATE</p></div></section>
<section className="ticker"><span>FDA REGISTERED</span><span>18 MONTHS</span><span>AMAZON ★ 4.8</span><span>WORLDWIDE EXPORT</span></section>
<section className="collection" id="products"><div className="sectionTitle"><p>01 / COLLECTION</p><h2><Lines>{t.collection}</Lines></h2></div><div className="cards">{t.cards.map((c,i)=><article key={c[0]}><div className={`art art${i+1}`}>{i===0?<div className="sheets"><i/><i/><b>A4</b></div>:i===1?<div className="miniCake"><span>YOUR<br/>PHOTO</span></div>:<div className="cookies"><i>C</i><i>S</i><i>♥</i></div>}<em>0{i+1}</em></div><small>{c[2]}</small><h3>{c[0]}</h3><p>{c[1]}</p><a href={store}>VIEW PRODUCT →</a></article>)}</div></section>
<section className="why" id="ideas"><div className="whyTitle"><p>02 / WHY CAKE SALON</p><h2><Lines>{t.why}</Lines></h2></div><div className="features">{t.features.map(f=><article key={f[0]}><b>{f[0]}</b><h3>{f[1]}</h3><p>{f[2]}</p></article>)}</div></section>
<section className="story" id="brand"><div className="storyVisual"><div className="orbit"><b>CS</b><span>SEOUL — WORLD</span></div></div><div className="storyText"><p>03 / OUR STORY</p><h2><Lines>{t.story}</Lines></h2><div className="rule"/><p className="storyDesc">{t.storyDesc}</p><a href={store}>DISCOVER CAKE SALON ↗</a></div></section>
<section className="end"><p>MAKE YOUR MOMENT EDIBLE</p><h2><Lines>{t.final}</Lines></h2><a className="cta dark" href={store}>{t.cta}<b>↗</b></a><a className="phone" href="tel:0806647077">{t.call}</a></section>
<footer><a className="logo" href="#top"><b>CAKE</b><i>SALON</i></a><p>© 2026 C&amp;C CORPORATION · SEOUL</p><a href={store}>SMARTSTORE ↗</a></footer>
</main>}
