import type { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  return [{
    url: "https://cakesalon.kr",
    lastModified: new Date(),
    changeFrequency: "weekly",
    priority: 1,
    images: [
      "https://cakesalon.kr/cake-renaissance.jpeg",
      "https://cakesalon.kr/cake-salon-a4-25.png",
      "https://cakesalon.kr/cake-floral.jpeg",
      "https://cakesalon.kr/coffee-i-love-you.png",
      "https://cakesalon.kr/coffee-congrats.png",
      "https://cakesalon.kr/coffee-thank-you.png",
      "https://cakesalon.kr/cocktail-cheers.png",
      "https://cakesalon.kr/cocktail-celebrate.png",
      "https://cakesalon.kr/cocktail-anniversary.png",
      "https://cakesalon.kr/candy-love.png",
      "https://cakesalon.kr/candy-celebrate.png",
      "https://cakesalon.kr/candy-thank-you.png",
      "https://cakesalon.kr/cotton-face-bunny.png",
      "https://cakesalon.kr/cotton-face-bear.png",
      "https://cakesalon.kr/cotton-face-cat.png",
      "https://cakesalon.kr/cookie-love.png",
      "https://cakesalon.kr/cookie-celebrate.png",
      "https://cakesalon.kr/cookie-thank-you.png",
      "https://cakesalon.kr/macaron-anniversary.png",
      "https://cakesalon.kr/macaron-celebrate.png",
      "https://cakesalon.kr/macaron-floral.png",
      "https://cakesalon.kr/macaron-disc-anniversary.png",
      "https://cakesalon.kr/macaron-disc-celebrate.png",
      "https://cakesalon.kr/macaron-disc-floral.png",
      "https://cakesalon.kr/macaron-thin-anniversary.png",
      "https://cakesalon.kr/macaron-thin-celebrate.png",
      "https://cakesalon.kr/macaron-thin-floral.png",
      "https://cakesalon.kr/bungeoppang-cake.png",
      "https://cakesalon.kr/bungeoppang-cake-rainbow.png",
      "https://cakesalon.kr/fruit-cake.png",
    ],
  }];
}
